hostNetwork: true

crds:
  installMethod: helm

tetragon:
  debug: true
  enableK8sAPI: true
  enablePolicyFilter: true
  exportRateLimit: -1
  exportAllowList: |
    {"event_set":["PROCESS_EXEC","PROCESS_EXIT","PROCESS_KPROBE","PROCESS_UPROBE","PROCESS_TRACEPOINT","PROCESS_LSM"]}
  grpc:
    enabled: true
    address: localhost:54321
  securityContext:
    privileged: true

tetragonOperator:
  enabled: true
  forceUpdateCRDs: true
  tracingPolicy:
    enabled: true
