CREATE TABLE IF NOT EXISTS clients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  country_of_birth TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS client_sensitive_data (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  email_address TEXT NOT NULL UNIQUE,
  social_insurance_number TEXT NOT NULL,
  credit_card_information TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (name) REFERENCES clients(name) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE OR REPLACE VIEW sensitive_data AS
SELECT
  id,
  name,
  email_address,
  social_insurance_number,
  credit_card_information,
  created_at
FROM client_sensitive_data;
